name: Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches:    
    - main

jobs:
  call-CI-part:
    uses: ./.github/workflows/continuous-integration.yaml
    with:
      action_name: pull_request