name: Release to Azure

on:
  push:
    branches:
    - main
  
jobs:
  call_CI_part:
    uses: ./.github/workflows/continuous-integration.yaml
    with:
      action_name: release_azure
    secrets:
      TOAST_APPKEY: ${{ secrets.TOAST_APPKEY }}
      TOAST_SECRETKEY: ${{ secrets.TOAST_SECRETKEY }}
      REQUEST_ID: ${{ secrets.REQUEST_ID }}
      SENDER_NO: ${{ secrets.SENDER_NO }}
      RECIPIENT_NO: ${{ secrets.RECIPIENT_NO }}

  call_CD_azure:
    needs: 
    - call_CI_part
    uses: ./.github/workflows/continuous-deployment.yaml
    with:
      action_name: release_azure
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_ENVIRONMENT_CODE: ${{ secrets.AZURE_ENVIRONMENT_CODE }}
      AZURE_LOCATION_CODE: ${{ secrets.AZURE_LOCATION_CODE }}
      AZURE_RESOURCE_NAME: ${{ secrets.AZURE_RESOURCE_NAME }}

    
   