name: Release to GitHub

on:
  push:
    tags:
    - 'v*'

jobs:
  call_CI_part:
    uses: ./.github/workflows/continuous-integration.yaml
    with:
      action_name: release_github
    secrets:
      TOAST_APPKEY: ${{ secrets.TOAST_APPKEY }}
      TOAST_SECRETKEY: ${{ secrets.TOAST_SECRETKEY }}
      REQUEST_ID: ${{ secrets.REQUEST_ID }}
      SENDER_NO: ${{ secrets.SENDER_NO }}
      RECIPIENT_NO: ${{ secrets.RECIPIENT_NO }}
    
  call_CD_github:
    needs: 
    - call_CI_part
    uses: ./.github/workflows/continuous-deployment.yaml
    with:
      action_name: release_github
      tag: ${{ github.ref }}