name: Release to Azure

on:
  push:
    branches:
    - main
  
jobs:
  call_CI_part:
    uses: ./.github/workflows/continuous-integration.yaml
    with:
      action_name: release_azure

  call_CD_azure:
    needs: 
    - call_CI_part
    uses: ./.github/workflows/continuous-deployment.yaml
    with:
      action_name: release_azure
    
   